spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: fuel-service
              uri: lb://FUEL-SERVICE
              predicates:
                - Path=/api/fuel/**
            - id: price-comments-service
              uri: lb://PRICE-COMMENT-SERVICE
              predicates:
                  - Path=api/price-comments/**
gateway:
  logging:
    request-cache-limit: 10240

management:
  tracing:
    sampling:
      probability: 1.0