spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: fuel-service
              uri: lb://FUEL-SERVICE
              predicates:
                - Path=/api/fuel/**
            - id: price-comments-service
              uri: lb://PRICE-COMMENT-SERVICE
              predicates:
                  - Path=api/price-comments/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/csh-apps/protocol/openid-connect/certs

management:
  tracing:
    sampling:
      probability: 1.0